# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  
# Define commands
commands:
  print_pipeline_id:
    description: "Prints the Circle CI Workflow ID from its environment variable"
    parameters:
      to:
        type: string
        default: $CIRCLE_WORKFLOW_ID
    steps:
      - run: echo << parameters.to >>

# Define jobs
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo Hello

  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo World

  print_env_var:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo $MY_NAME
      
  call_a_comand:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id:
            to: ${CIRCLE_WORKFLOW_ID}
            
  fail_for_test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: return 1
      - run:
          name: Upload Failed Tests
          command: curl --data fail_tests.log http://example.com/error_logs
          when: on_fail

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - print_hello
      - print_world:
          requires:
            - print_hello
      - print_env_var
      - call_a_comand
      - fail_for_test